export const FETCH_PLACE_DATA = 'FETCH_PLACE_DATA';
export const FETCH_PLACE_CATEGORIES = 'FETCH_PLACE_CATEGORIES';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const ATTEMPT_LOGIN = 'ATTEMPT_LOGIN';
